text_sensor:
  # Spider Plant
  - platform: homeassistant
    id: plant_spider_plant_status
    entity_id: plant.spider_plant
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_spider_plant_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_spider_plant_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_spider_plant_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_spider_plant_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_spider_plant_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

  # Jade Plant
  - platform: homeassistant
    id: plant_jade_plant_status
    entity_id: plant.jade_plant
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_jade_plant_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_jade_plant_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_jade_plant_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_jade_plant_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_jade_plant_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

  # Pothos
  - platform: homeassistant
    id: plant_pothos_status
    entity_id: plant.pothos
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_pothos_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_pothos_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_pothos_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_pothos_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_pothos_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

  # Begonia
  - platform: homeassistant
    id: plant_begonia_status
    entity_id: plant.begonia
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_begonia_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_begonia_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_begonia_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_begonia_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_begonia_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

  # Monstera
  - platform: homeassistant
    id: plant_monstera_status
    entity_id: plant.monstera
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_monstera_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_monstera_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_monstera_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_monstera_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_monstera_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

  # Nerve Plant
  - platform: homeassistant
    id: plant_nerve_plant_status
    entity_id: plant.nerve_plant
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_nerve_plant_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_nerve_plant_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_nerve_plant_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_nerve_plant_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_nerve_plant_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

  # Aglaonema
  - platform: homeassistant
    id: plant_aglaonema_status
    entity_id: plant.aglaonema
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_aglaonema_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_aglaonema_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_aglaonema_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_aglaonema_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_aglaonema_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

  # Croton
  - platform: homeassistant
    id: plant_croton_status
    entity_id: plant.croton
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_croton_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_croton_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_croton_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_croton_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_croton_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

  # Elephant Ears
  - platform: homeassistant
    id: plant_elephant_ears_status
    entity_id: plant.elephant_ears
    attribute: moisture_status
    on_value:
      - lambda: |-
          lv_label_set_text(id(lbl_plant_elephant_ears_status), x.c_str());
          std::string val = x;
          std::transform(val.begin(), val.end(), val.begin(), ::tolower);
          if (val == "ok") {
            lv_obj_set_style_text_color(id(lbl_plant_elephant_ears_status), lv_color_hex(0x10B981), LV_PART_MAIN);
          } else if (val == "low") {
            lv_obj_set_style_text_color(id(lbl_plant_elephant_ears_status), lv_color_hex(0xEF4444), LV_PART_MAIN);
          } else if (val == "high") {
            lv_obj_set_style_text_color(id(lbl_plant_elephant_ears_status), lv_color_hex(0x3B82F6), LV_PART_MAIN);
          } else {
            lv_obj_set_style_text_color(id(lbl_plant_elephant_ears_status), lv_color_hex(0xFFFFFF), LV_PART_MAIN);
          }

sensor:
  # Spider Plant
  - platform: homeassistant
    id: plant_spider_plant_moisture
    entity_id: sensor.spider_plant_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_spider_plant_moisture), "%d%%", (int)x);

  # Jade Plant
  - platform: homeassistant
    id: plant_jade_plant_moisture
    entity_id: sensor.jade_plant_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_jade_plant_moisture), "%d%%", (int)x);

  # Pothos
  - platform: homeassistant
    id: plant_pothos_moisture
    entity_id: sensor.pothos_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_pothos_moisture), "%d%%", (int)x);

  # Begonia
  - platform: homeassistant
    id: plant_begonia_moisture
    entity_id: sensor.begonia_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_begonia_moisture), "%d%%", (int)x);

  # Monstera
  - platform: homeassistant
    id: plant_monstera_moisture
    entity_id: sensor.monstera_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_monstera_moisture), "%d%%", (int)x);

  # Nerve Plant
  - platform: homeassistant
    id: plant_nerve_plant_moisture
    entity_id: sensor.nerve_plant_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_nerve_plant_moisture), "%d%%", (int)x);

  # Aglaonema
  - platform: homeassistant
    id: plant_aglaonema_moisture
    entity_id: sensor.aglaonema_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_aglaonema_moisture), "%d%%", (int)x);

  # Croton
  - platform: homeassistant
    id: plant_croton_moisture
    entity_id: sensor.croton_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_croton_moisture), "%d%%", (int)x);

  # Elephant Ears
  - platform: homeassistant
    id: plant_elephant_ears_moisture
    entity_id: sensor.elephant_ears_soil_moisture
    on_value:
      - lambda: lv_label_set_text_fmt(id(lbl_plant_elephant_ears_moisture), "%d%%", (int)x);